python-wrapping: comment out code that causes issues
results in:
error: constexpr variable 'as_object_track' must be initialized by a constant expression
not sure why since the same code compiles when not wrapping.

Possibly missing some compiler flag.