python: Add -fsized-deallocation in clang arguments
clang (that is used internally by castxml) fails with
error: call to '__builtin_operator_delete' selects non-usual deallocation function